In [47]:
import pandas as pd
import numpy as np

**Q1. Pandas version - What version of Pandas did you install?**

In [48]:
pd.__version__

'3.0.6'

**Getting the data**

In [49]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

**Q2. Records count - How many records are in the dataset?**

In [50]:
df.shape

(10000, 11)

**Q3. Fuel types - How many fuel types are presented in the dataset?**


In [51]:
df.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')

In [52]:
df['fuel_type']

0       Gasoline
1         Diesel
2       Gasoline
3       Gasoline
4         Diesel
          ...   
9995    Gasoline
9996    Gasoline
9997    Gasoline
9998      Hybrid
9999      Diesel
Name: fuel_type, Length: 10000, dtype: str

In [53]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

**Q4. Missing values - How many columns in the dataset have missing values?**

In [54]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

**Q5. Max fuel efficiency - What's the maximum fuel efficiency of cars from Asia?**

In [56]:
df['origin'].unique()

<StringArray>
['Europe', 'Asia', 'USA']
Length: 3, dtype: str

In [57]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

**Q6. Median value of horsepower 
1- Find the median value of the horsepower column in the dataset.**

In [58]:
df['horsepower'].median()

np.float64(254.0)

**2- Next, calculate the most frequent value of the same horsepower column.**

In [59]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

3- Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [60]:
df['horsepower'] = df['horsepower'].fillna(252.0)

In [61]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

4- Now, calculate the median value of horsepower once again.

In [62]:
df['horsepower'].median()

np.float64(252.0)

Q7. Sum of weights 
1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.

In [63]:
df_asia = df[df['origin'] == 'Asia']
X = df_asia[['vehicle_weight', 'model_year']].head(7).values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [64]:
XTX = np.dot(X.T, X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

6. Invert XTX.

In [65]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [66]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

In [67]:
w = np.dot(np.dot(XTX_inv, X.T), y)
w

array([0.13644777, 0.2327492 ])

In [68]:
w.sum()

np.float64(0.36919696904925486)